POST http://localhost:8080/api/workflow/execute
Content-Type: application/json

{
  "user": "kitti.admin",
  "Workflow_ID": "TSD-01",
  "Event_Type": "Cash_Dividend",
  "amount": 15000000.00,
  "Net_Amount": 15000000.00,
  "Account_ID": "WALLET-VIP"
}

### VOTE 1 (Senior Manager)
POST http://localhost:8080/api/consensus/vote
Content-Type: application/json

{
  "txId": "API-b7597ee8",
  "approver": "Senior_Manager"
}

### VOTE 2 (Director - Just in case it needs 2!)
POST http://localhost:8080/api/consensus/vote
Content-Type: application/json

{
  "txId": "API-b7597ee8",
  "approver": "Director"
}