### 🚀 Execute Workflow (Dynamic JSON with Security & Money)
POST http://localhost:8080/api/workflow/execute
Content-Type: application/json

{
  "user": "system_admin",
  "Workflow_ID": "TSD-01",
  "Registrar_Code": "TSD",
  "AMOUNT": 50000.00,
  "CURRENCY": "THB",
  "INVESTOR_ID": "ACCT-001",
  "WALLET_ID": "W-998877",
  "TARGET_BANK": "BBL_TH"
}