package com.tsd.platform.spi

/**
 * A neutral, atomic instruction generated by a Cartridge.
 */
interface InstructionCommand {
    val name: String
    fun execute(context: ExecutionContext): CommandResult
}